spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: db/schema-h2.sql
    data: db/h2-data.sql
    url: jdbc:h2:mem:test
    username: root
    password: test
mybatis-plus:
  mapperLocations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.youke.entities

